### ISSUE TITLE
Data url is broken?

### ISSUE THREAD

**Issue by kristyrobledo** [njtierney/ozroaddeaths#12]
I think the URL may be broken for the data download as I am getting the following error. 

> library(ozroaddeaths)
> library(dplyr)
> library(ggplot2)
> library(lubridate)
> crashes <- oz_road_fatal_crash()
Error in open.connection(con, "rb") : HTTP error 404.
> fatalities <- oz_road_fatalities()
Error in open.connection(con, "rb") : HTTP error 404.

**Comment by njtierney** [comment]
Resolves!
