### ISSUE TITLE
Transfer repo to personal account?

### ISSUE THREAD

**Issue by maelle** [njtierney/ozroaddeaths#16]
@njtierney @kristyrobledo et al :wave: according to our [recently created package curation policy](https://devguide.ropensci.org/curationpolicy.html#incubator-packages) this repo should now be transferred to either one of your personal accounts, or the ropensci-archive organization.

If you don't answer within one month, I'll transfer the repository to ropensci-archive, after which you could still email me to transfer the repo to a personal account.

Thank you!

**Comment by njtierney** [comment]
Hi Maëlle!

Sure, you can transfer it to mine 😄

**Comment by maelle** [comment]
@njtierney thanks for your answer! Transfer requested :-)
