### ISSUE TITLE
ggplot2 is used in vignettes, but not used in the package

### ISSUE THREAD

**Issue by johann-wagner** [njtierney/ozroaddeaths#47]
I recently deleted all my R packages and only installed `devtools` and all the dependencies for `ozroaddeaths`. It seems like `ggplot2` is used in vignettes, but not used in `ozroaddeaths` as a dependency. This has caused the following error when running `check()` and `build()`.

Unsure, whether this is a major issue, as it is likely most people will have installed `ggplot2`, but just wanting to highlight this, as I'm unsure if `ggplot2` should indeed be in the dependencies even if it is only used in the vignettes.

```
─  installing the package to build vignettes
E  creating vignettes (4.1s)
   --- re-building 'getting-started.Rmd' using rmarkdown
   
   Quitting from lines 47-56 [load-library] (getting-started.Rmd)
   Error: processing vignette 'getting-started.Rmd' failed with diagnostics:
   there is no package called 'ggplot2'
   --- failed re-building 'getting-started.Rmd'
   
   SUMMARY: processing the following file failed:
     'getting-started.Rmd'
   
   Error: Vignette re-building failed.
   Execution halted
Error in `(function (command = NULL, args = character(), error_on_status = TRUE, …`:
! System command 'Rcmd.exe' failed
---
Exit status: 1
stdout & stderr: <printed>
---
Type .Last.error to see the more details.
```

**Comment by johann-wagner** [comment]
Nevermind :/

https://r-pkgs.org/description.html#sec-description-imports-suggests

**Comment by njtierney** [comment]
You found the right resource :)
